export const INCREMENT_SCORE = 'LEO-SPRINT/INCREMENT_SCORE';
export const TOGGLE_START = 'LEO-SPRINT/TOGGLE_START';
export const TOGGLE_END = 'LEO-SPRINT/TOGGLE_END';
export const HANDLE_WRONG = 'LEO-SPRINT/HANDLE_WRONG';
export const HANDLE_RIGHT = 'LEO-SPRINT/HANDLE_RIGHT';
export const CLEAR_GAME = 'LEO-SPRINT/CLEAR_GAME';
export const SET_LEOSPRINTPAGE = 'LEO-SPRINT/SET_LEOSPRINTPAGE';

export const CHANGE_PAGE = 'DICTIONARY/CHANGE_PAGE';
export const SET_GROUP = 'DICTIONARY/SET_GROUP';
export const SET_PAGE = 'DICTIONARY/SET_PAGE';
export const SET_PAGINATEDWORDSET = 'DICTIONARY/SET_PAGINATEDWORDSET';
export const SET_PAGESWORD = 'DICTIONARY/SET_PAGESWORD';
export const DELETE_WORD = 'DICTIONARY/DELETE_WORD';
export const SET_PAGEBUTTONS = 'DICTIONARY/SET_PAGEBUTTONS';

export const SET_SECTION = 'VOCABULARY/SET_SECTION';
export const SET_VOCABULARYGROUP = 'VOCABULARY/SET_VOCABULARYGROUP';
export const SET_VOCABULARYPAGEBUTTONS = 'VOCABULARY/SET_VOCABULARYPAGEBUTTONS';
export const SET_VOCABULARYPAGINATEDWORDSET = 'VOCABULARY/SET_VOCABULARYPAGINATEDWORDSET';
export const SET_VOCABULARYPAGESWORD = 'VOCABULARY/SET_VOCABULARYPAGESWORD';
export const SET_VOCABULARYPAGE = 'VOCABULARY/SET_VOCABULARYPAGE';
export const CHANGE_VOCABULARYPAGE = 'VOCABULARY/CHANGE_VOCABULARYPAGE';

export const CHANGE_SETTINGS = 'SETTINGS/CHANGE_SETTINGS';
export const SET_ISTRANLASTED = 'SETTINGS/SET_ISTRANLASTED';
export const SET_ISBUTTONSHOWED = 'SETTINGS/SET_ISBUTTONSHOWED';

export const SET_STATISTIC = 'STATISTIC/SET_STATISTIC';
export const SET_COUNT = 'STATISTIC/SET_COUNT';
